AWSTemplateFormatVersion: '2010-09-09'
Description: 'NOAA Federated Data Lake - Glue Crawlers for Automatic Schema Discovery'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

  DataLakeBucket:
    Type: String
    Default: ''
    Description: S3 bucket name for data lake (leave empty to auto-generate)

  CrawlerSchedule:
    Type: String
    Default: 'cron(0 */6 * * ? *)'
    Description: Schedule for crawlers (default every 6 hours)

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Environment Configuration
        Parameters:
          - Environment
      - Label:
          default: Data Lake Configuration
        Parameters:
          - DataLakeBucket
      - Label:
          default: Crawler Schedule
        Parameters:
          - CrawlerSchedule

Conditions:
  CreateBucketName: !Equals [!Ref DataLakeBucket, '']

Resources:
  # ========================================
  # IAM ROLE FOR GLUE CRAWLERS
  # ========================================

  GlueCrawlerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'noaa-glue-crawler-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: GlueCrawlerS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:GetBucketLocation
                Resource:
                  - !Sub
                    - 'arn:aws:s3:::${BucketName}'
                    - BucketName: !If
                      - CreateBucketName
                      - !Sub 'noaa-federated-lake-${AWS::AccountId}-${Environment}'
                      - !Ref DataLakeBucket
                  - !Sub
                    - 'arn:aws:s3:::${BucketName}/*'
                    - BucketName: !If
                      - CreateBucketName
                      - !Sub 'noaa-federated-lake-${AWS::AccountId}-${Environment}'
                      - !Ref DataLakeBucket
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws-glue/crawlers*'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: NOAA-Federated-Lake
        - Key: ManagedBy
          Value: CloudFormation

  # ========================================
  # GLUE DATABASES
  # ========================================

  BronzeDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Sub 'noaa_bronze_${Environment}'
        Description: NOAA Bronze Layer (Raw Data) - Auto-generated by Glue Crawlers
        LocationUri: !Sub
          - 's3://${BucketName}/bronze/'
          - BucketName: !If
            - CreateBucketName
            - !Sub 'noaa-federated-lake-${AWS::AccountId}-${Environment}'
            - !Ref DataLakeBucket

  GoldDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Sub 'noaa_gold_${Environment}'
        Description: NOAA Gold Layer (Analytics-Ready) - Auto-generated by Glue Crawlers
        LocationUri: !Sub
          - 's3://${BucketName}/gold/'
          - BucketName: !If
            - CreateBucketName
            - !Sub 'noaa-federated-lake-${AWS::AccountId}-${Environment}'
            - !Ref DataLakeBucket

  # ========================================
  # BRONZE LAYER CRAWLERS
  # ========================================

  BronzeAtmosphericCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Sub 'noaa-bronze-atmospheric-${Environment}'
      Role: !GetAtt GlueCrawlerRole.Arn
      DatabaseName: !Ref BronzeDatabase
      Description: Crawls Bronze atmospheric data
      Schedule:
        ScheduleExpression: !Ref CrawlerSchedule
      Targets:
        S3Targets:
          - Path: !Sub
            - 's3://${BucketName}/bronze/atmospheric/'
            - BucketName: !If
              - CreateBucketName
              - !Sub 'noaa-federated-lake-${AWS::AccountId}-${Environment}'
              - !Ref DataLakeBucket
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG
      Configuration: '{"Version":1.0,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}}'
      Tags:
        Environment: !Ref Environment
        Project: NOAA-Federated-Lake
        Pond: atmospheric
        Layer: bronze

  BronzeOceanicCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Sub 'noaa-bronze-oceanic-${Environment}'
      Role: !GetAtt GlueCrawlerRole.Arn
      DatabaseName: !Ref BronzeDatabase
      Description: Crawls Bronze oceanic data
      Schedule:
        ScheduleExpression: !Ref CrawlerSchedule
      Targets:
        S3Targets:
          - Path: !Sub
            - 's3://${BucketName}/bronze/oceanic/'
            - BucketName: !If
              - CreateBucketName
              - !Sub 'noaa-federated-lake-${AWS::AccountId}-${Environment}'
              - !Ref DataLakeBucket
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG
      Configuration: '{"Version":1.0,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}}'
      Tags:
        Environment: !Ref Environment
        Project: NOAA-Federated-Lake
        Pond: oceanic
        Layer: bronze

  BronzeBuoyCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Sub 'noaa-bronze-buoy-${Environment}'
      Role: !GetAtt GlueCrawlerRole.Arn
      DatabaseName: !Ref BronzeDatabase
      Description: Crawls Bronze buoy data
      Schedule:
        ScheduleExpression: !Ref CrawlerSchedule
      Targets:
        S3Targets:
          - Path: !Sub
            - 's3://${BucketName}/bronze/buoy/'
            - BucketName: !If
              - CreateBucketName
              - !Sub 'noaa-federated-lake-${AWS::AccountId}-${Environment}'
              - !Ref DataLakeBucket
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG
      Configuration: '{"Version":1.0,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}}'
      Tags:
        Environment: !Ref Environment
        Project: NOAA-Federated-Lake
        Pond: buoy
        Layer: bronze

  BronzeClimateCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Sub 'noaa-bronze-climate-${Environment}'
      Role: !GetAtt GlueCrawlerRole.Arn
      DatabaseName: !Ref BronzeDatabase
      Description: Crawls Bronze climate data
      Schedule:
        ScheduleExpression: !Ref CrawlerSchedule
      Targets:
        S3Targets:
          - Path: !Sub
            - 's3://${BucketName}/bronze/climate/'
            - BucketName: !If
              - CreateBucketName
              - !Sub 'noaa-federated-lake-${AWS::AccountId}-${Environment}'
              - !Ref DataLakeBucket
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG
      Configuration: '{"Version":1.0,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}}'
      Tags:
        Environment: !Ref Environment
        Project: NOAA-Federated-Lake
        Pond: climate
        Layer: bronze

  BronzeTerrestrialCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Sub 'noaa-bronze-terrestrial-${Environment}'
      Role: !GetAtt GlueCrawlerRole.Arn
      DatabaseName: !Ref BronzeDatabase
      Description: Crawls Bronze terrestrial data
      Schedule:
        ScheduleExpression: !Ref CrawlerSchedule
      Targets:
        S3Targets:
          - Path: !Sub
            - 's3://${BucketName}/bronze/terrestrial/'
            - BucketName: !If
              - CreateBucketName
              - !Sub 'noaa-federated-lake-${AWS::AccountId}-${Environment}'
              - !Ref DataLakeBucket
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG
      Configuration: '{"Version":1.0,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}}'
      Tags:
        Environment: !Ref Environment
        Project: NOAA-Federated-Lake
        Pond: terrestrial
        Layer: bronze

  BronzeSpatialCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Sub 'noaa-bronze-spatial-${Environment}'
      Role: !GetAtt GlueCrawlerRole.Arn
      DatabaseName: !Ref BronzeDatabase
      Description: Crawls Bronze spatial data
      Schedule:
        ScheduleExpression: !Ref CrawlerSchedule
      Targets:
        S3Targets:
          - Path: !Sub
            - 's3://${BucketName}/bronze/spatial/'
            - BucketName: !If
              - CreateBucketName
              - !Sub 'noaa-federated-lake-${AWS::AccountId}-${Environment}'
              - !Ref DataLakeBucket
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG
      Configuration: '{"Version":1.0,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}}'
      Tags:
        Environment: !Ref Environment
        Project: NOAA-Federated-Lake
        Pond: spatial
        Layer: bronze

  # ========================================
  # GOLD LAYER CRAWLERS
  # ========================================

  GoldAtmosphericCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Sub 'noaa-gold-atmospheric-${Environment}'
      Role: !GetAtt GlueCrawlerRole.Arn
      DatabaseName: !Ref GoldDatabase
      Description: Crawls Gold atmospheric data
      Schedule:
        ScheduleExpression: !Ref CrawlerSchedule
      Targets:
        S3Targets:
          - Path: !Sub
            - 's3://${BucketName}/gold/atmospheric/'
            - BucketName: !If
              - CreateBucketName
              - !Sub 'noaa-federated-lake-${AWS::AccountId}-${Environment}'
              - !Ref DataLakeBucket
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG
      Configuration: '{"Version":1.0,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}}'
      Tags:
        Environment: !Ref Environment
        Project: NOAA-Federated-Lake
        Pond: atmospheric
        Layer: gold

  GoldOceanicCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Sub 'noaa-gold-oceanic-${Environment}'
      Role: !GetAtt GlueCrawlerRole.Arn
      DatabaseName: !Ref GoldDatabase
      Description: Crawls Gold oceanic data
      Schedule:
        ScheduleExpression: !Ref CrawlerSchedule
      Targets:
        S3Targets:
          - Path: !Sub
            - 's3://${BucketName}/gold/oceanic/'
            - BucketName: !If
              - CreateBucketName
              - !Sub 'noaa-federated-lake-${AWS::AccountId}-${Environment}'
              - !Ref DataLakeBucket
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG
      Configuration: '{"Version":1.0,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}}'
      Tags:
        Environment: !Ref Environment
        Project: NOAA-Federated-Lake
        Pond: oceanic
        Layer: gold

  GoldBuoyCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Sub 'noaa-gold-buoy-${Environment}'
      Role: !GetAtt GlueCrawlerRole.Arn
      DatabaseName: !Ref GoldDatabase
      Description: Crawls Gold buoy data
      Schedule:
        ScheduleExpression: !Ref CrawlerSchedule
      Targets:
        S3Targets:
          - Path: !Sub
            - 's3://${BucketName}/gold/buoy/'
            - BucketName: !If
              - CreateBucketName
              - !Sub 'noaa-federated-lake-${AWS::AccountId}-${Environment}'
              - !Ref DataLakeBucket
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG
      Configuration: '{"Version":1.0,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}}'
      Tags:
        Environment: !Ref Environment
        Project: NOAA-Federated-Lake
        Pond: buoy
        Layer: gold

  GoldClimateCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Sub 'noaa-gold-climate-${Environment}'
      Role: !GetAtt GlueCrawlerRole.Arn
      DatabaseName: !Ref GoldDatabase
      Description: Crawls Gold climate data
      Schedule:
        ScheduleExpression: !Ref CrawlerSchedule
      Targets:
        S3Targets:
          - Path: !Sub
            - 's3://${BucketName}/gold/climate/'
            - BucketName: !If
              - CreateBucketName
              - !Sub 'noaa-federated-lake-${AWS::AccountId}-${Environment}'
              - !Ref DataLakeBucket
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG
      Configuration: '{"Version":1.0,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}}'
      Tags:
        Environment: !Ref Environment
        Project: NOAA-Federated-Lake
        Pond: climate
        Layer: gold

  GoldTerrestrialCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Sub 'noaa-gold-terrestrial-${Environment}'
      Role: !GetAtt GlueCrawlerRole.Arn
      DatabaseName: !Ref GoldDatabase
      Description: Crawls Gold terrestrial data
      Schedule:
        ScheduleExpression: !Ref CrawlerSchedule
      Targets:
        S3Targets:
          - Path: !Sub
            - 's3://${BucketName}/gold/terrestrial/'
            - BucketName: !If
              - CreateBucketName
              - !Sub 'noaa-federated-lake-${AWS::AccountId}-${Environment}'
              - !Ref DataLakeBucket
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG
      Configuration: '{"Version":1.0,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}}'
      Tags:
        Environment: !Ref Environment
        Project: NOAA-Federated-Lake
        Pond: terrestrial
        Layer: gold

  GoldSpatialCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Sub 'noaa-gold-spatial-${Environment}'
      Role: !GetAtt GlueCrawlerRole.Arn
      DatabaseName: !Ref GoldDatabase
      Description: Crawls Gold spatial data
      Schedule:
        ScheduleExpression: !Ref CrawlerSchedule
      Targets:
        S3Targets:
          - Path: !Sub
            - 's3://${BucketName}/gold/spatial/'
            - BucketName: !If
              - CreateBucketName
              - !Sub 'noaa-federated-lake-${AWS::AccountId}-${Environment}'
              - !Ref DataLakeBucket
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG
      Configuration: '{"Version":1.0,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}}'
      Tags:
        Environment: !Ref Environment
        Project: NOAA-Federated-Lake
        Pond: spatial
        Layer: gold

Outputs:
  GlueCrawlerRoleArn:
    Description: ARN of the Glue Crawler IAM Role
    Value: !GetAtt GlueCrawlerRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-GlueCrawlerRoleArn'

  BronzeDatabaseName:
    Description: Name of the Bronze Glue Database
    Value: !Ref BronzeDatabase
    Export:
      Name: !Sub '${AWS::StackName}-BronzeDatabaseName'

  GoldDatabaseName:
    Description: Name of the Gold Glue Database
    Value: !Ref GoldDatabase
    Export:
      Name: !Sub '${AWS::StackName}-GoldDatabaseName'

  BronzeCrawlers:
    Description: Names of Bronze layer crawlers
    Value: !Sub |
      ${BronzeAtmosphericCrawler}
      ${BronzeOceanicCrawler}
      ${BronzeBuoyCrawler}
      ${BronzeClimateCrawler}
      ${BronzeTerrestrialCrawler}
      ${BronzeSpatialCrawler}

  GoldCrawlers:
    Description: Names of Gold layer crawlers
    Value: !Sub |
      ${GoldAtmosphericCrawler}
      ${GoldOceanicCrawler}
      ${GoldBuoyCrawler}
      ${GoldClimateCrawler}
      ${GoldTerrestrialCrawler}
      ${GoldSpatialCrawler}

  CrawlerSchedule:
    Description: Schedule expression for crawlers
    Value: !Ref CrawlerSchedule

  TotalCrawlersDeployed:
    Description: Total number of crawlers deployed
    Value: '12'
